server:
  port: 8001
#mybatis配置
mybatis:
  type-aliases-package: classpath:com.yyh.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud01?useUnicode=true&characterEncoding=utf8
    username: root
    password: 883203

#eureka的配置  向eureka注册中心注册
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #修改注册中心页面Status位置的描述信息
    prefer-ip-address: true #当鼠标指在服务上面时，在左下角的提示：desktop2lsd5ka:8001->ip地址
#注册中心页面info配置
info:
  app.name: yyh-springcloud
  company.name: blog.yyh.com